### PR TITLE
parser: fix auth parsing

### LINKED ISSUE #170: parsing: auth
Currently we parse single instance of `opaque_auth` in header of `call` request:
```
async fn parse_authentication(&mut self) -> Result<AuthStat> {
        match self.buffer.parse_with_retry(auth).await?.flavor {
            AuthFlavor::None => Ok(AuthStat::Ok),
            _ => {
                unimplemented!()
            }
        }
    }
```

When RFC says, that there are 2: `cre`d and `verf`:
```
struct call_body {
           unsigned int rpcvers;       /* must be equal to two (2) */
           unsigned int prog;
           unsigned int vers;
           unsigned int proc;
           opaque_auth cred;
           opaque_auth verf;
           /* procedure-specific parameters start here */
 };
```

### PR DESCRIPTION
**Pull request by MikhailSvirukov**
Resolves:  #170

### CODE REVIEW

**Comment by VadimYarovoy** [comment]
@MikhailSvirukov CI failed

File: src/parser/parser_struct.rs [hunk 1]
```diff
@@ -198,10 +198,7 @@ impl<A: Allocator, S: AsyncRead + Unpin> RpcParser<A, S> {
         let version = self.buffer.parse_with_retry(u32).await?;
         let procedure = self.buffer.parse_with_retry(u32).await?;
 
-        let auth_status = self.parse_authentication().await?;
-        if auth_status != AuthStat::Ok {
-            return Err(Error::AuthError(auth_status));
-        }
+        let (_cred, _verf) = self.parse_authentication().await?;
```
Comment (VadimYarovoy) [inline src/parser/parser_struct.rs:202]: add TODO wiht issue link

File: src/parser/parser_struct.rs [hunk 2]
```diff
@@ -212,15 +209,10 @@ impl<A: Allocator, S: AsyncRead + Unpin> RpcParser<A, S> {
...
-    /// Returns [`AuthStat::Ok`] if authentication succeeds, or an error
+    /// Returns a pair of [`OpaqueAuth`] if authentication succeeds, or an error
     /// if authentication fails or an I/O error occurs.
-    async fn parse_authentication(&mut self) -> Result<AuthStat> {
-        match self.buffer.parse_with_retry(auth).await?.flavor {
-            AuthFlavor::None => Ok(AuthStat::Ok),
-            _ => {
-                unimplemented!()
-            }
-        }
```
Comment (VadimYarovoy) [inline src/parser/parser_struct.rs:223]: why removed? Now we are fail open, because  `Sys/Short/Dh/RpcSecGss` will pass here but no handle for them is supported

File: src/parser/parser_struct.rs [hunk 3]
```diff
@@ -212,15 +209,10 @@ impl<A: Allocator, S: AsyncRead + Unpin> RpcParser<A, S> {
...
+    async fn parse_authentication(&mut self) -> Result<(OpaqueAuth, OpaqueAuth)> {
+        Ok((self.buffer.parse_with_retry(auth).await?, self.buffer.parse_with_retry(auth).await?))
     }
```
Comment (VadimYarovoy) [inline src/parser/parser_struct.rs:225]:
```suggestion
    async fn parse_authentication(&mut self) -> Result<(OpaqueAuth, OpaqueAuth)> {
        let cred = self.buffer.parse_with_retry(auth).await?;
        let verf = self.buffer.parse_with_retry(auth).await?;

        if !matches!(cred.flavor, AuthFlavor::None) || !cred.body.is_empty() {
            return Err(Error::AuthError(AuthStat::BadCred));
        }

        if !matches!(verf.flavor, AuthFlavor::None) || !verf.body.is_empty() {
            return Err(Error::AuthError(AuthStat::BadVerf));
        }

        Ok((cred, verf))
    }
```

File: src/parser/tests/parser_struct.rs
Comment (VadimYarovoy) [inline src/parser/tests/parser_struct.rs:1]: add some tests for  - https://github.com/RMamonts/nfs-mamont/pull/171/changes#r2941388235, for example

```rs
#[tokio::test]
async fn parse_rejects_non_none_cred_auth() {
    let frame = nfs_call_frame(RpcBody::Call as u32, RPC_VERSION, AUTH_SYS, FSSTAT, |buf| {
        buf.extend_from_slice(&fsstat_args([1, 2, 3, 4, 5, 6, 7, 8]));
    });
    let socket = MockSocket::new(frame.as_slice());
    let alloc = Arc::new(Mutex::new(MockAllocator::new(0)));
    let mut parser = RpcParser::with_capacity(socket, alloc, 0x40);

    let result = parser.next_message().await;
    assert!(matches!(result, Err(Error::AuthError(AuthStat::BadCred))));
}

#[tokio::test]
async fn parse_rejects_non_none_verf_auth() {
    let mut payload = Vec::new();
    push_u32(&mut payload, XID);
    push_u32(&mut payload, RpcBody::Call as u32);
    push_u32(&mut payload, RPC_VERSION);
    push_u32(&mut payload, NFS_PROGRAM);
    push_u32(&mut payload, NFS_VERSION);
    push_u32(&mut payload, FSSTAT);

    // cred: AUTH_NONE with empty body
    push_u32(&mut payload, AUTH_NONE);
    push_u32(&mut payload, 0);

    // verifier: AUTH_SYS with empty body
    push_u32(&mut payload, AUTH_SYS);
    push_u32(&mut payload, 0);

    payload.extend_from_slice(&fsstat_args([1, 2, 3, 4, 5, 6, 7, 8]));

    let mut frame = Vec::new();
    let payload_len: u32 = payload.len().try_into().unwrap();
    push_u32(&mut frame, FRAGMENT_HEADER_MASK | payload_len);
    frame.extend_from_slice(&payload);

    let socket = MockSocket::new(frame.as_slice());
    let alloc = Arc::new(Mutex::new(MockAllocator::new(0)));
    let mut parser = RpcParser::with_capacity(socket, alloc, 0x40);

    let result = parser.next_message().await;
    assert!(matches!(result, Err(Error::AuthError(AuthStat::BadVerf))));
}

```

**Review by VadimYarovoy — DISMISSED** [review]
Some things to fix

**Review by VadimYarovoy — APPROVED** [review]
